### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by moondawg69** [lorenzodianni/SidebarJS#1]
Tried viewing this on: http://www.cssscript.com/demo/mobile-app-like-drawer-navigation-pure-javascript-sidebarjs/

And also locally. Safari Version 9.1.1 (11601.6.16)

Nothing happens on toggle click.

Console:

[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function) (sidebar.js:6)
[Error] ReferenceError: Can't find variable: SidebarJS
	global code (mobile-app-like-drawer-navigation-pure-javascript-sidebarjs:66)

**Comment by lorenzodianni** [comment]
**SidebarJS is still in alpha.**
**The entire repository is work in progress.**

If you want to see a preview, run it on Chrome (not Safari, Firefox or others).
I will let you know when will be released!

**Comment by lorenzodianni** [comment]
Just released!
